### ISSUE TITLE
1.0.8 still asks for 'DiscUtils.BootConfig', version: '0.16.0-alpha0017'

### ISSUE THREAD

**Issue by marvias17** [rishooty/Q9xS#1]
I am getting same error with 1.0.7 and 1.0.8

```
D:\slipstream\w98\q9xs>"c:\program files\dotnet\dotnet" Q9xS.dll d:\slipstream\w98\updates\ d:\slipstream\w98\iso\win98se.iso
Error:
  An assembly specified in the application dependencies manifest (Q9xS.deps.json) was not found:
    package: 'DiscUtils.BootConfig', version: '0.16.0-alpha0017'
    path: 'lib/netstandard2.0/DiscUtils.BootConfig.dll'
```

when I compare files between 1.0.7 and 1.0.8 theyre all identical except some path in Q9xS.runtimeconfig.dev.json

**Comment by rishooty** [comment]
Apologies, try now. This was my first dotnet core project, so I didn't know that they had to be published rather than just built in order to use third party dependencies. 

It's also frustrating that I can't exactly test it without installing and uninstalling the SDK/Visual Studio. Let me know if 1.0.9 works, it looks like it has the necessary DiscUtils dependencies now.

**Comment by marvias17** [comment]
now it works fine, thanks :) 

as for the testing, probably easiest is to have a separate VM and test there.
